name:                pokemon-species-db
version:             0.1.0.0
github:              "salenius/pokemon-species-db"
license:             BSD3
author:              "Tommi Salenius"
maintainer:          "tommisalenius@gmail.com"
copyright:           "2022 Tommi Salenius"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pokemon-species-db#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  pokemon-species-db-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pokemon-species-db

tests:
  pokemon-species-db-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pokemon-species-db
